--mobs:spawn_specific("mobs_fallout:moonheron", {"air"}, {"air"},0, 17, 100, 150000, 2, -5610, -3500)
mobs:register_spawn("mobs_fallout:moonheron", {"air"}, 5, -1, 150000, 2, 100)
mobs:register_mob("mobs_fallout:moonheron", {
	type = "monster",
	group_attack = true,
	pathfinding = true,
	hp_max = 23,
	hp_min = 22,
	collisionbox = {-0.45, -0.3, -0.45, 0.45, 0.3, 0.45},
	visual = "mesh",
	mesh = "moonheron.x",
	textures = {{"moonheron.png"}},
	visual_size = {x=10, y=10},
	view_range = 35,
	rotate = 270,
	walk_velocity = 2,
	run_velocity = 3,
	fall_speed = 0,
	stepheight = 3,
	sounds = {
		random = "uloboros",
		distance =40,
	},
	damage = 3,
	jump = true,
	drops = {
		{name = "default:papyrus", chance = 1, min = 0, max = 1},
		{name = "default:glue", chance = 19, min = 0, max = 1},
	    {name = "mobs_fallout:meat_raw", chance = 1, min = 2, max = 3},
	},
	armor = 100,
	floats = 1,
	water_damage = 5,
	lava_damage = 5,
	light_damage = 5,
	fly = true,
	attack_type = "dogfight",
	animation = {
		speed_normal = 25,
		speed_run = 35,
		stand_start = 140,
		stand_end = 200,
		walk_start = 20,
		walk_end = 60,
		run_start = 20,
		run_end = 60,
		punch_start = 80,
		punch_end = 120,
	}
})
