minetest.register_on_newplayer(function(player)
	--print("on_newplayer")
		minetest.log("action", "Giving initial stuff to player "..player:get_player_name())
		player:get_inventory():add_item('main', 'default:sword_bronze 1')
		player:get_inventory():add_item('main', 'default:torch 5')
--		player:get_inventory():add_item('main', 'thirsty:steel_canteen 1')
		player:get_inventory():add_item('main', 'shooter:rifle 1')
		player:get_inventory():add_item('main', 'default:pick_steel 1')
		--player:get_inventory():add_item('main', 'default:sapling 1')
		player:get_inventory():add_item('main', 'default:wood 3')
		player:get_inventory():add_item('main', 'farming:bread 3')
		player:get_inventory():add_item('main', 'shooter:ammo 1')
end)

